const defaultUsers = [
  { id: 'u1', name: 'سارة أحمد', role: 'manager', title: 'مديرة المشاريع', initials: 'سأ', color: '#2563eb', email: 'sara@injaz.local', password: '123456' },
  { id: 'u2', name: 'محمد علي', role: 'employee', title: 'مصمم واجهات', initials: 'مع', color: '#8b5cf6', email: 'mohamed@injaz.local', password: '123456' },
  { id: 'u3', name: 'نور خالد', role: 'employee', title: 'مطور واجهات', initials: 'نخ', color: '#059669', email: 'nour@injaz.local', password: '123456' },
  { id: 'u4', name: 'عمر يوسف', role: 'employee', title: 'مسؤول تسويق', initials: 'عي', color: '#ea580c', email: 'omar@injaz.local', password: '123456' }
];
let users = JSON.parse(localStorage.getItem('injaz-users') || 'null') || defaultUsers;

const statusMeta = {
  todo: { label: 'لم تبدأ', className: 'todo' },
  progress: { label: 'قيد التنفيذ', className: 'progress' },
  review: { label: 'بانتظار المراجعة', className: 'review' },
  done: { label: 'مكتملة', className: 'done' }
};
const priorityMeta = {
  high: { label: 'عالية', className: 'high' },
  medium: { label: 'متوسطة', className: 'medium' },
  low: { label: 'منخفضة', className: 'low' }
};

const seedTasks = [
  { id: 't1', title: 'تصميم الصفحة الرئيسية الجديدة', description: 'إعداد تصميم متجاوب للصفحة الرئيسية بما يتماشى مع هوية العلامة التجارية الجديدة.', priority: 'high', startDate: '2026-08-23', dueDate: '2026-09-02', status: 'progress', assignees: ['u2', 'u3'], createdBy: 'u1', createdAt: '2026-08-22T09:00:00', logs: [{ id:'l1', userId:'u2', text:'أنهيت تصميم القسم الرئيسي وبطاقات الخدمات.', hours: 4, createdAt:'2026-08-28T11:30:00' }], attachments: [], history: [] },
  { id: 't2', title: 'تجهيز تقرير أداء أغسطس', description: 'جمع مؤشرات الأداء ومصادر الزيارات وتحضير ملخص قابل للمشاركة مع الإدارة.', priority: 'medium', startDate: '2026-08-24', dueDate: '2026-08-30', status: 'review', assignees: ['u4'], createdBy: 'u1', createdAt: '2026-08-23T12:00:00', logs: [], attachments: [], history: [] },
  { id: 't3', title: 'اختبار رحلة التسجيل', description: 'مراجعة رحلة إنشاء الحساب وتوثيق الأخطاء والملاحظات قبل الإطلاق.', priority: 'high', startDate: '2026-08-20', dueDate: '2026-08-28', status: 'todo', assignees: ['u3'], createdBy: 'u1', createdAt: '2026-08-19T10:00:00', logs: [], attachments: [], history: [] },
  { id: 't4', title: 'تحديث دليل العلامة التجارية', description: 'إضافة الإرشادات الخاصة باستخدام الألوان والخطوط الجديدة.', priority: 'low', startDate: '2026-08-21', dueDate: '2026-09-06', status: 'done', assignees: ['u2'], createdBy: 'u1', createdAt: '2026-08-20T09:00:00', logs: [], attachments: [], history: [] }
];

let state = { currentUserId: sessionStorage.getItem('injaz-current-user'), activePage: 'dashboard', selectedTaskId: null, filter: 'all', search: '', modal: null };
let tasks = JSON.parse(localStorage.getItem('injaz-tasks') || 'null') || seedTasks;
let readNotifications = new Set(JSON.parse(localStorage.getItem('injaz-read-notifications') || '[]'));
tasks.forEach(t => { t.history ||= []; t.logs ||= []; t.attachments ||= []; });
const app = document.querySelector('#app');
const currentUser = () => users.find(u => u.id === state.currentUserId);
const isManager = () => currentUser()?.role === 'manager';
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date = (value) => new Intl.DateTimeFormat('ar-EG', { day:'numeric', month:'short', year:'numeric' }).format(new Date(value));
const time = (value) => new Intl.DateTimeFormat('ar-EG', { day:'numeric', month:'short', hour:'numeric', minute:'2-digit' }).format(new Date(value));
const save = () => localStorage.setItem('injaz-tasks', JSON.stringify(tasks));
const saveUsers = () => localStorage.setItem('injaz-users', JSON.stringify(users));
const saveReadNotifications = () => localStorage.setItem('injaz-read-notifications', JSON.stringify([...readNotifications]));
const user = id => users.find(u => u.id === id) || { id, name:'حساب محذوف', initials:'—', color:'#94a3b8', title:'', email:'' };
const initials = id => { const u=user(id); return `<span class="avatar" style="--avatar:${u.color}" title="${esc(u.name)}">${u.initials}</span>`; };
const taskStatus = key => `<span class="badge status ${statusMeta[key].className}"><i></i>${statusMeta[key].label}</span>`;
const priority = key => `<span class="priority ${priorityMeta[key].className}">${priorityMeta[key].label}</span>`;
const addHistory = (task, text, type='update') => task.history.unshift({ id: crypto.randomUUID(), userId: currentUser().id, text, type, createdAt: new Date().toISOString() });
const notify = text => { const el=document.createElement('div'); el.className='toast'; el.textContent=text; document.body.append(el); setTimeout(()=>el.remove(), 2600); };

function navItem(page, icon, label) { return `<button class="nav-item ${state.activePage===page?'active':''}" data-page="${page}"><span>${icon}</span>${label}</button>`; }
function shell(content) {
 const me=currentUser();
 return `<div class="layout"><aside class="sidebar"><div class="brand"><span class="brand-mark">✓</span><span>إنجاز</span></div><div class="workspace">مساحة العمل</div><nav>${navItem('dashboard','▦','لوحة التحكم')}${navItem('tasks','☷','المهام')}${isManager()?navItem('users','♙','الفريق'):''}${isManager()?navItem('accounts','⊕','حسابات الموظفين'):''}</nav><div class="sidebar-bottom"><div class="user-mini">${initials(me.id)}<div><strong>${me.name}</strong><small>${me.title}</small></div><button id="logout" title="تسجيل الخروج">↪</button></div></div></aside><main><header><button class="mobile-menu" id="mobile-menu">☰</button><div><h1>${pageTitle()}</h1><p>${isManager() ? 'تابع العمل ونظّم مهام فريقك بسهولة' : 'أهلاً بك، إليك المهام التي تنتظرك اليوم'}</p></div><div class="header-actions"><button class="icon-btn" id="notifications" aria-label="الإشعارات">♧<b>${unreadNotifications().length}</b></button>${isManager()?'<button class="primary" data-action="new-task">+ مهمة جديدة</button>':''}</div></header><section class="content">${content}</section></main></div>${state.modal ? modal() : ''}`;
}
function pageTitle(){ return state.activePage==='dashboard' ? (isManager()?'لوحة التحكم':'مهامي') : state.activePage==='tasks'?'كل المهام':state.activePage==='users'?'الفريق':state.activePage==='accounts'?'حسابات الموظفين':state.activePage==='notifications'?'الإشعارات':'تفاصيل المهمة'; }
function taskCard(t, compact=false) { const overdue = t.dueDate < new Date().toISOString().slice(0,10) && t.status !== 'done'; return `<article class="task-card ${compact?'compact':''}" data-task="${t.id}"><div class="task-top">${priority(t.priority)}${taskStatus(t.status)}</div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><div class="task-footer"><div class="avatars">${t.assignees.slice(0,3).map(initials).join('')}${t.assignees.length>3?`<span class="avatar more">+${t.assignees.length-3}</span>`:''}</div><span class="due ${overdue?'overdue':''}">◷ ${overdue?'متأخرة · ':''}${date(t.dueDate)}</span></div></article>`; }
function dashboard(){
 const accessible=taskList(), total=accessible.length, done=accessible.filter(t=>t.status==='done').length, progress=accessible.filter(t=>t.status==='progress').length, overdue=accessible.filter(t=>t.dueDate<new Date().toISOString().slice(0,10)&&t.status!=='done').length, recent=accessible.filter(t=>t.status!=='done').slice(0,4);
 const managementInsights=isManager()?`<div class="dashboard-bottom"><div class="panel"><div class="panel-head"><h2>تقدم الفريق</h2><span>هذا الأسبوع</span></div>${users.filter(u=>u.role==='employee').map(u=>{const assigned=tasks.filter(t=>t.assignees.includes(u.id)),completed=assigned.filter(t=>t.status==='done').length,pct=assigned.length?Math.round(completed/assigned.length*100):0;return `<div class="member-progress">${initials(u.id)}<div class="grow"><div><strong>${u.name}</strong><span>${completed} من ${assigned.length} مهام مكتملة</span></div><div class="progress-bar"><i style="width:${pct}%"></i></div></div><b>${pct}%</b></div>`}).join('')}</div><div class="panel activity"><div class="panel-head"><h2>آخر النشاطات</h2></div>${allHistory().slice(0,5).map(h=>`<div class="activity-row">${initials(h.userId)}<div><strong>${user(h.userId).name}</strong> <span>${esc(h.text)}</span><small>${time(h.createdAt)}</small></div></div>`).join('')||'<div class="empty">لا توجد نشاطات بعد</div>'}</div></div>`:'';
 return shell(`<div class="kpis"><div class="kpi blue"><span>☷</span><div><small>إجمالي المهام</small><strong>${total}</strong><em>مهمة نشطة</em></div></div><div class="kpi orange"><span>◷</span><div><small>قيد التنفيذ</small><strong>${progress}</strong><em>تحتاج متابعة</em></div></div><div class="kpi green"><span>✓</span><div><small>المهام المكتملة</small><strong>${done}</strong><em>${total?Math.round(done/total*100):0}% من الإجمالي</em></div></div><div class="kpi red"><span>!</span><div><small>مهام متأخرة</small><strong>${overdue}</strong><em>${overdue?'تحتاج اهتماماً':'كل شيء على ما يرام'}</em></div></div></div><div class="section-head"><div><h2>${isManager()?'نظرة على المهام':'المهام المفتوحة'}</h2><p>آخر المهام التي تحتاج إلى عمل</p></div><button class="link-btn" data-page="tasks">عرض الكل ←</button></div><div class="task-grid">${recent.length?recent.map(t=>taskCard(t)).join(''):'<div class="empty">لا توجد مهام مفتوحة الآن. عمل رائع!</div>'}</div>${managementInsights}`);
}
function taskList(){return isManager()?tasks:tasks.filter(t=>t.assignees.includes(currentUser().id));}
function tasksPage(){let list=taskList().filter(t=>(state.filter==='all'||t.status===state.filter)&&(`${t.title} ${t.description}`).includes(state.search)); return shell(`<div class="toolbar"><div class="search">⌕<input id="search" placeholder="ابحث عن مهمة..." value="${esc(state.search)}"></div><div class="filters">${[['all','الكل'],['todo','لم تبدأ'],['progress','قيد التنفيذ'],['review','مراجعة'],['done','مكتملة']].map(([k,l])=>`<button class="filter ${state.filter===k?'active':''}" data-filter="${k}">${l}</button>`).join('')}</div></div><div class="tasks-list">${list.length?list.map(t=>taskCard(t)).join(''):'<div class="empty">لا توجد مهام مطابقة لهذا البحث.</div>'}</div>`);}
function usersPage(){return shell(`<div class="team-grid">${users.map(u=>{let count=tasks.filter(t=>t.assignees.includes(u.id));return `<div class="member-card">${initials(u.id)}<div><h3>${u.name}</h3><p>${u.title}</p><span class="role ${u.role}">${u.role==='manager'?'مدير':'موظف'}</span></div><strong>${count.length}<small>مهام</small></strong></div>`}).join('')}</div>`);}
function loginPage(){return `<main class="login-page"><section class="login-brand"><div class="brand"><span class="brand-mark">✓</span><span>إنجاز</span></div><h1>منظّم العمل لفريقك</h1><p>تابع المهام، سجّل الإنجاز، واجعل كل الفريق على المسار نفسه.</p></section><form class="login-card" id="login-form"><h2>تسجيل الدخول</h2><p>أدخل بيانات حسابك للمتابعة.</p><label>البريد الإلكتروني<input name="email" type="email" required placeholder="name@company.com"></label><label>كلمة المرور<input name="password" type="password" required placeholder="••••••••"></label><button class="primary">دخول إلى النظام</button><div class="demo-login"><strong>حساب المدير للتجربة</strong><span>sara@injaz.local</span><span>كلمة المرور: 123456</span></div></form></main>`;}
function accountsPage(){const employees=users.filter(u=>u.role==='employee'), editing=state.editingUserId?user(state.editingUserId):null;return shell(`<div class="accounts-layout"><section class="panel"><div class="panel-head"><div><h2>${editing?'تعديل حساب الموظف':'إنشاء حساب موظف'}</h2><p>${editing?'اترك كلمة المرور فارغة إذا لم ترغب بتغييرها.':'أضف موظفاً جديداً ليتمكن من تسجيل الدخول واستلام المهام.'}</p></div></div>${editing?`<form id="edit-account-form" class="account-form"><label>الاسم الكامل<input name="name" required value="${esc(editing.name)}"></label><label>المسمى الوظيفي<input name="title" required value="${esc(editing.title)}"></label><label>البريد الإلكتروني<input name="email" type="email" required value="${esc(editing.email)}"></label><label>كلمة المرور الجديدة<input name="password" type="password" minlength="6" placeholder="اتركها فارغة"></label><button type="button" class="secondary" id="cancel-edit">إلغاء</button><button class="primary">حفظ التعديلات</button></form>`:`<form id="account-form" class="account-form"><label>الاسم الكامل<input name="name" required placeholder="مثال: أحمد سامي"></label><label>المسمى الوظيفي<input name="title" required placeholder="مثال: مطور واجهات"></label><label>البريد الإلكتروني<input name="email" type="email" required placeholder="ahmed@company.com"></label><label>كلمة المرور<input name="password" type="password" minlength="6" required placeholder="6 أحرف على الأقل"></label><button class="primary">إنشاء الحساب</button></form>`}</section><section class="panel"><div class="panel-head"><div><h2>حسابات الموظفين</h2><p>${employees.length} حسابات فعّالة</p></div></div><div class="account-table">${employees.map(u=>`<div class="account-row">${initials(u.id)}<div><strong>${u.name}</strong><small>${u.email}</small></div><span>${u.title}</span><div class="account-actions"><button class="edit-account" data-edit-account="${u.id}">تعديل</button><button class="delete-account" data-delete-account="${u.id}">حذف</button></div></div>`).join('')}</div></section></div>`);}
function taskDetails(){const t=tasks.find(x=>x.id===state.selectedTaskId);if(!t){state.activePage='tasks';return tasksPage();}const canEdit=isManager()||t.assignees.includes(currentUser().id);const history=[...t.history,...t.logs.map(l=>({...l,text:`أضاف سجل عمل: ${l.text}`,type:'log'})),...t.attachments.map(a=>({...a,text:`أرفق ملفاً: ${a.name}`,type:'attachment'}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return shell(`<button class="back" data-page="tasks">→ العودة إلى المهام</button><div class="detail-layout"><article class="detail-main"><div class="detail-title"><div><div class="inline-badges">${priority(t.priority)}${taskStatus(t.status)}</div><h2>${esc(t.title)}</h2></div>${canEdit?`<select class="status-select" data-status-task="${t.id}">${Object.entries(statusMeta).map(([k,v])=>`<option value="${k}" ${t.status===k?'selected':''}>${v.label}</option>`).join('')}</select>`:''}</div><section><h3>الوصف</h3><p class="description">${esc(t.description)}</p></section><section class="detail-info"><div><small>تاريخ البدء</small><strong>${date(t.startDate)}</strong></div><div><small>تاريخ الاستحقاق</small><strong>${date(t.dueDate)}</strong></div><div><small>المسند إليهم</small><span class="avatars">${t.assignees.map(initials).join('')}</span></div></section><section><div class="section-title"><h3>سجل العمل</h3><span>${t.logs.reduce((sum,l)=>sum+Number(l.hours),0)} ساعة مسجلة</span></div>${canEdit?`<form id="log-form" class="log-form"><input name="hours" type="number" min="0.25" step="0.25" placeholder="الساعات" required><input name="text" placeholder="ما الذي أنجزته؟" required><button class="primary">إضافة سجل</button></form>`:''}<div class="log-list">${t.logs.length?t.logs.map(l=>`<div class="log-item">${initials(l.userId)}<div><strong>${user(l.userId).name}</strong><p>${esc(l.text)}</p><small>${time(l.createdAt)}</small></div><b>${l.hours} س</b></div>`).join(''):'<div class="muted">لم يتم تسجيل أي وقت بعد.</div>'}</div></section><section><div class="section-title"><h3>الملفات والمرفقات</h3></div>${canEdit?'<label class="upload"><input id="file-input" type="file" multiple>⇧ أضف ملفات أو صوراً</label>':''}<div class="attachments">${t.attachments.map(a=>`<a class="attachment" href="${a.url}" download="${esc(a.name)}">${a.type.startsWith('image/')?'▧':'▤'}<span>${esc(a.name)}</span><small>${a.size}</small></a>`).join('')||'<div class="muted">لا توجد مرفقات.</div>'}</div></section></article><aside class="activity-panel"><h3>سجل النشاط</h3>${history.length?history.map(h=>`<div class="timeline"><i></i><div><strong>${user(h.userId).name}</strong><p>${esc(h.text)}</p><small>${time(h.createdAt)}</small></div></div>`).join(''):'<div class="muted">سيظهر سجل تغييرات المهمة هنا.</div>'}</aside></div>`);}
function taskEditorPage(){const t=tasks.find(x=>x.id===state.selectedTaskId);if(!t||!isManager()){state.activePage='tasks';return tasksPage();}return shell(`<button class="back" data-page="detail">→ العودة إلى تفاصيل المهمة</button><form id="edit-task-form" class="panel task-editor"><div class="panel-head"><div><h2>تعديل المهمة</h2><p>عدّل تفاصيل المهمة والإسناد حسب احتياج الفريق.</p></div></div><label>عنوان المهمة<input name="title" required value="${esc(t.title)}"></label><label>الوصف<textarea name="description" required>${esc(t.description)}</textarea></label><div class="form-grid"><label>الأولوية<select name="priority">${Object.entries(priorityMeta).map(([k,v])=>`<option value="${k}" ${t.priority===k?'selected':''}>${v.label}</option>`).join('')}</select></label><label>الحالة<select name="status">${Object.entries(statusMeta).map(([k,v])=>`<option value="${k}" ${t.status===k?'selected':''}>${v.label}</option>`).join('')}</select></label><label>تاريخ البدء<input name="startDate" type="date" required value="${t.startDate}"></label><label>تاريخ الاستحقاق<input name="dueDate" type="date" required value="${t.dueDate}"></label></div><fieldset><legend>إسناد المهمة إلى</legend><div class="assignees">${users.filter(u=>u.role==='employee').map(u=>`<label class="assign"><input type="checkbox" name="assignees" value="${u.id}" ${t.assignees.includes(u.id)?'checked':''}>${initials(u.id)}<span>${u.name}</span></label>`).join('')}</div></fieldset><div class="modal-actions"><button type="button" class="secondary" data-page="detail">إلغاء</button><button class="primary">حفظ التعديلات</button></div></form>`);}
function allHistory(){return tasks.flatMap(t=>[...t.history,...t.logs.map(l=>({...l,text:`سجل ${l.hours} ساعات في «${t.title}»`})),...t.attachments.map(a=>({...a,text:`أرفق ${a.name} في «${t.title}»`}))]).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));}
function notifications(){return taskList().filter(t=>t.dueDate<=new Date(Date.now()+3*86400000).toISOString().slice(0,10)&&t.status!=='done');}
function unreadNotifications(){return notifications().filter(t=>!readNotifications.has(t.id));}
function notificationsPage(){const items=notifications(),today=new Date().toISOString().slice(0,10);return shell(`<div class="notifications-page"><div class="panel"><div class="panel-head"><div><h2>الإشعارات</h2><p>المهام التي تحتاج إلى متابعتك الآن.</p></div><span class="notification-count">${unreadNotifications().length} جديدة</span></div>${items.length?`<div class="notification-list">${items.map(t=>{const overdue=t.dueDate<today;return `<button class="notification-item" data-task="${t.id}"><span class="notice-icon ${overdue?'danger':'warning'}">${overdue?'!':'◷'}</span><span><strong>${overdue?'مهمة متأخرة':'موعد المهمة قريب'}</strong><p>${esc(t.title)}</p><small>${overdue?`تجاوزت تاريخ الاستحقاق ${date(t.dueDate)}`:`تاريخ الاستحقاق: ${date(t.dueDate)}`}</small></span><b>عرض ←</b></button>`}).join('')}</div>`:'<div class="empty">لا توجد إشعارات جديدة. كل شيء تحت السيطرة.</div>'}</div></div>`);}
function modal(){return `<div class="modal-wrap"><div class="modal-backdrop" data-action="close-modal"></div><form class="modal" id="task-form"><div class="modal-head"><div><h2>إنشاء مهمة جديدة</h2><p>أضف التفاصيل ثم حدّد أعضاء الفريق المسؤولين عنها.</p></div><button type="button" class="close" data-action="close-modal">×</button></div><label>عنوان المهمة<input name="title" required placeholder="مثال: إعداد خطة الإطلاق"></label><label>الوصف<textarea name="description" required placeholder="اكتب وصفاً واضحاً لما يجب إنجازه..."></textarea></label><div class="form-grid"><label>الأولوية<select name="priority"><option value="high">عالية</option><option value="medium" selected>متوسطة</option><option value="low">منخفضة</option></select></label><label>الحالة<select name="status">${Object.entries(statusMeta).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}</select></label><label>تاريخ البدء<input name="startDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>تاريخ الاستحقاق<input name="dueDate" type="date" required></label></div><fieldset><legend>إسناد إلى</legend><div class="assignees">${users.filter(u=>u.role==='employee').map(u=>`<label class="assign"><input type="checkbox" name="assignees" value="${u.id}">${initials(u.id)}<span>${u.name}</span></label>`).join('')}</div></fieldset><div class="modal-actions"><button type="button" class="secondary" data-action="close-modal">إلغاء</button><button class="primary">إنشاء المهمة</button></div></form></div>`;}
function render(){if(!currentUser()){app.innerHTML=loginPage();bind();return}if((state.activePage==='users'||state.activePage==='accounts')&&!isManager())state.activePage='dashboard';let content=state.activePage==='dashboard'?dashboard():state.activePage==='tasks'?tasksPage():state.activePage==='users'?usersPage():state.activePage==='accounts'&&isManager()?accountsPage():state.activePage==='notifications'?notificationsPage():state.activePage==='edit-task'?taskEditorPage():taskDetails();app.innerHTML=content;bind();bindAccountActions();bindTaskEditActions();}
function bindAccountActions(){document.querySelector('#edit-account-form')?.addEventListener('submit',updateAccount);document.querySelector('#cancel-edit')?.addEventListener('click',()=>{state.editingUserId=null;render()});document.querySelectorAll('[data-edit-account]').forEach(e=>e.onclick=()=>{state.editingUserId=e.dataset.editAccount;render()});document.querySelectorAll('[data-delete-account]').forEach(e=>e.onclick=()=>deleteAccount(e.dataset.deleteAccount));}
function bindTaskEditActions(){document.querySelectorAll('[data-page="detail"]').forEach(e=>e.onclick=()=>{state.activePage='detail';render()});if(state.activePage==='detail'&&isManager()){const title=document.querySelector('.detail-title');const button=document.createElement('button');button.className='secondary edit-task-button';button.textContent='تعديل المهمة';button.onclick=()=>{state.activePage='edit-task';render()};title.append(button);}document.querySelector('#edit-task-form')?.addEventListener('submit',updateTask);}
function bind(){document.querySelector('#login-form')?.addEventListener('submit',login);document.querySelectorAll('[data-page]').forEach(e=>e.onclick=()=>{state.activePage=e.dataset.page;state.selectedTaskId=null;render()});document.querySelectorAll('[data-task]').forEach(e=>e.onclick=()=>{state.selectedTaskId=e.dataset.task;state.activePage='detail';render()});document.querySelectorAll('[data-filter]').forEach(e=>e.onclick=()=>{state.filter=e.dataset.filter;render()});document.querySelector('[data-action="new-task"]')?.addEventListener('click',()=>{state.modal='new';render()});document.querySelectorAll('[data-action="close-modal"]').forEach(e=>e.onclick=()=>{state.modal=null;render()});document.querySelector('#search')?.addEventListener('input',e=>{state.search=e.target.value;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(state.search.length,state.search.length)});document.querySelector('#task-form')?.addEventListener('submit',createTask);document.querySelector('#account-form')?.addEventListener('submit',createAccount);document.querySelector('[data-status-task]')?.addEventListener('change',updateStatus);document.querySelector('#log-form')?.addEventListener('submit',addLog);document.querySelector('#file-input')?.addEventListener('change',addFiles);document.querySelector('#logout')?.addEventListener('click',()=>{sessionStorage.removeItem('injaz-current-user');state.currentUserId=null;state.activePage='dashboard';render()});document.querySelector('#notifications')?.addEventListener('click',()=>{notifications().forEach(t=>readNotifications.add(t.id));saveReadNotifications();state.activePage='notifications';state.selectedTaskId=null;render()});document.querySelector('#mobile-menu')?.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('show'));}
function createTask(e){e.preventDefault();const f=new FormData(e.target), t={id:crypto.randomUUID(), title:f.get('title').trim(),description:f.get('description').trim(),priority:f.get('priority'),status:f.get('status'),startDate:f.get('startDate'),dueDate:f.get('dueDate'),assignees:f.getAll('assignees'),createdBy:currentUser().id,createdAt:new Date().toISOString(),logs:[],attachments:[],history:[]};if(!t.assignees.length){notify('اختر موظفاً واحداً على الأقل.');return} if(t.dueDate<t.startDate){notify('تاريخ الاستحقاق يجب أن يكون بعد تاريخ البدء.');return} addHistory(t,'أنشأ المهمة','create');tasks.unshift(t);save();state.modal=null;state.selectedTaskId=t.id;state.activePage='detail';notify('تم إنشاء المهمة وإسنادها بنجاح.');render();}
function updateTask(e){e.preventDefault();const t=tasks.find(x=>x.id===state.selectedTaskId),f=new FormData(e.target),newAssignees=f.getAll('assignees');if(!newAssignees.length){notify('اختر موظفاً واحداً على الأقل.');return}if(f.get('dueDate')<f.get('startDate')){notify('تاريخ الاستحقاق يجب أن يكون بعد تاريخ البدء.');return}const oldAssignees=t.assignees;Object.assign(t,{title:f.get('title').trim(),description:f.get('description').trim(),priority:f.get('priority'),status:f.get('status'),startDate:f.get('startDate'),dueDate:f.get('dueDate'),assignees:newAssignees});const added=newAssignees.filter(id=>!oldAssignees.includes(id));const removed=oldAssignees.filter(id=>!newAssignees.includes(id));addHistory(t,added.length?`عدّل المهمة وأسندها إلى ${added.map(id=>user(id).name).join('، ')}`:'عدّل تفاصيل المهمة');if(removed.length)addHistory(t,`ألغى إسناد المهمة عن ${removed.map(id=>user(id).name).join('، ')}`);save();state.activePage='detail';notify('تم حفظ تعديلات المهمة.');render();}
function login(e){e.preventDefault();const f=new FormData(e.target), found=users.find(u=>u.email.toLowerCase()===f.get('email').trim().toLowerCase()&&u.password===f.get('password'));if(!found){notify('البريد الإلكتروني أو كلمة المرور غير صحيحة.');return}state.currentUserId=found.id;sessionStorage.setItem('injaz-current-user',found.id);state.activePage='dashboard';notify(`مرحباً بك، ${found.name}`);render();}
function createAccount(e){e.preventDefault();const f=new FormData(e.target), email=f.get('email').trim().toLowerCase();if(users.some(u=>u.email.toLowerCase()===email)){notify('هذا البريد الإلكتروني مسجل بالفعل.');return}const name=f.get('name').trim(), initials=name.split(/\s+/).slice(0,2).map(n=>n[0]).join(''), colors=['#0f766e','#7c3aed','#c2410c','#be185d'];users.push({id:crypto.randomUUID(),name,role:'employee',title:f.get('title').trim(),initials,color:colors[users.length%colors.length],email,password:f.get('password')});saveUsers();notify('تم إنشاء حساب الموظف بنجاح.');render();}
function updateAccount(e){e.preventDefault();const f=new FormData(e.target), target=users.find(u=>u.id===state.editingUserId), email=f.get('email').trim().toLowerCase();if(users.some(u=>u.id!==target.id&&u.email.toLowerCase()===email)){notify('هذا البريد الإلكتروني مسجل بالفعل.');return}target.name=f.get('name').trim();target.title=f.get('title').trim();target.email=email;target.initials=target.name.split(/\s+/).slice(0,2).map(n=>n[0]).join('');if(f.get('password'))target.password=f.get('password');saveUsers();state.editingUserId=null;notify('تم حفظ تعديلات حساب الموظف.');render();}
function deleteAccount(id){const target=users.find(u=>u.id===id);if(!target)return;if(!confirm(`حذف حساب ${target.name}؟ سيتم إلغاء إسناد مهامه إليه.`))return;users=users.filter(u=>u.id!==id);tasks.forEach(t=>t.assignees=t.assignees.filter(assigneeId=>assigneeId!==id));saveUsers();save();state.editingUserId=null;notify('تم حذف الحساب وإلغاء إسناد مهامه.');render();}
function updateStatus(e){const t=tasks.find(x=>x.id===e.target.dataset.statusTask), old=t.status;t.status=e.target.value;addHistory(t,`غيّر الحالة من «${statusMeta[old].label}» إلى «${statusMeta[t.status].label}»`);save();notify('تم تحديث حالة المهمة.');render();}
function addLog(e){e.preventDefault();const t=tasks.find(x=>x.id===state.selectedTaskId), f=new FormData(e.target), log={id:crypto.randomUUID(),userId:currentUser().id,text:f.get('text').trim(),hours:Number(f.get('hours')),createdAt:new Date().toISOString()};t.logs.unshift(log);addHistory(t,'أضاف سجل عمل');save();notify('تمت إضافة سجل العمل.');render();}
function addFiles(e){const t=tasks.find(x=>x.id===state.selectedTaskId);[...e.target.files].forEach(file=>{const reader=new FileReader();reader.onload=()=>{t.attachments.unshift({id:crypto.randomUUID(),userId:currentUser().id,name:file.name,type:file.type||'application/octet-stream',size:file.size<1024*1024?`${Math.ceil(file.size/1024)} ك.ب`:`${(file.size/1024/1024).toFixed(1)} م.ب`,url:reader.result,createdAt:new Date().toISOString()});addHistory(t,`أرفق الملف «${file.name}»`);save();render();};reader.readAsDataURL(file);});}
render();
